# Generated by Django 4.2.5 on 2023-09-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'HOD'), (3, 'STUDENT'), (2, 'TEACHER')], default=1),
        ),
    ]
