# Generated by Django 4.2.4 on 2023-09-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attend_pic',
            name='attend_pic',
            field=models.FileField(null=True, upload_to='attend_pic'),
        ),
    ]
